# Generated by Django 4.0.4 on 2022-06-02 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0003_ride_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='derparture',
            new_name='departure',
        ),
    ]
