# Generated by Django 4.0.4 on 2022-06-04 18:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0005_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='interested',
            field=models.ManyToManyField(related_name='interested', to=settings.AUTH_USER_MODEL),
        ),
    ]
